# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170822_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=b'T\xc3\xadtulo')),
                ('content', models.TextField(verbose_name=b'Conte\xc3\xbado da P\xc3\xa1gina')),
            ],
            options={
                'verbose_name': 'P\xe1gina',
                'verbose_name_plural': 'P\xe1ginas',
            },
        ),
    ]
